name: Deploy website

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: [ tests ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Update image
        run: |
          mkdir "$HOME/.ssh"
          echo "${{ secrets.SSH_TOKEN }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          ssh -i "$HOME/.ssh/key" -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "./update.sh ${{ secrets.IMAGE_NAME }}"
